### ISSUE TITLE
use with assistant_library_demo.py

### ISSUE THREAD

**Issue by joseska** [senyoltw/custom-hotword-for-aiy-voicekit#1]
Hi....it´s posible to use with assistant_library_demo.py

thanks....

**Comment by senyoltw** [comment]
use this  https://github.com/senyoltw/custom-hotword-for-aiy-voicekit/blob/master/assistant_library_with_snowboy_demo.py

# how to use 
cd AIY-voice-kit-python
chmod a+x src/examples/voice/assistant_library_with_snowboy_demo.py
src/examples/voice/assistant_library_with_snowboy_demo.py src/mod/resources/alexa/alexa_02092017.umdl
