### ISSUE TITLE
New AIY version

### ISSUE THREAD

**Issue by Agicians** [senyoltw/custom-hotword-for-aiy-voicekit#3]
Hi,

I can't get this working with th new AIY version.
Can you provide some revision to this version? Thanks!

**Comment by shujaathaider** [comment]
> Hi,
> 
> I can't get this working with th new AIY version.
> Can you provide some revision to this version? Thanks!

Same issue :(

**Comment by senyoltw** [comment]
Merged pull requests running with the latest version so please try it.

**Comment by senyoltw** [comment]
https://github.com/senyoltw/custom-hotword-for-aiy-voicekit/pull/5
